# -*- coding: utf-8 -*-
{
    'name': 'Auditorias Grupoalvamex',
    'version': '10.0.0.1.0',
    'author': "Marco Gonzalez",
    'maintainer': '',
    'website': 'http://www.grupoalvamex.com/',
    'license': 'AGPL-3',
    'category': 'Survey',
    'summary': '',
    'depends': ['report','web_readonly_bypass','web'],
    'description': """ """,
    'demo': [],
    'test': [],
    'data': ['security/auditorias_grupoalvamex_security.xml',
            'security/ir.model.access.csv',            
            'views/auditoria_posturas_comerciales_view.xml',
            'views/auditoria_plantillas_view.xml',
            'views/auditoria_reporte.xml',
            'views/web_digital_sign_view.xml',
            'security/ir.model.access.csv',
            'data/auditorias_data.xml',],
    'css': ['static/src/css/auditoria.css'],
    'qweb': ['static/src/xml/digital_sign.xml'],
    'installable': True,
    'auto_install': False,
}
